spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/gastoclaro
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:f1eF0ihVn8xBf9qhll75xLic2jCmyyrCWM8gwpAjMpP}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}